// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwsPicJnpvgyLtiJePcZ4mvHvaSieTwsE',
    appId: '1:358871673337:web:4bbd0e4a8a41cc91ce3528',
    messagingSenderId: '358871673337',
    projectId: 'jobscanflutter',
    authDomain: 'jobscanflutter.firebaseapp.com',
    databaseURL: 'https://jobscanflutter-default-rtdb.firebaseio.com',
    storageBucket: 'jobscanflutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxZc7X4zo66IZIJ_OpJlKuB_-tIBUaMqQ',
    appId: '1:358871673337:android:6b29a523dd74a479ce3528',
    messagingSenderId: '358871673337',
    projectId: 'jobscanflutter',
    databaseURL: 'https://jobscanflutter-default-rtdb.firebaseio.com',
    storageBucket: 'jobscanflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUoI-AZgthgq1Mud8MZ43kR53xj34lHmo',
    appId: '1:358871673337:ios:255f1e3c38e705b4ce3528',
    messagingSenderId: '358871673337',
    projectId: 'jobscanflutter',
    databaseURL: 'https://jobscanflutter-default-rtdb.firebaseio.com',
    storageBucket: 'jobscanflutter.appspot.com',
    iosClientId: '358871673337-gilg7p7kpiuermrou86a70m2v2m2ssqr.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobscan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUoI-AZgthgq1Mud8MZ43kR53xj34lHmo',
    appId: '1:358871673337:ios:255f1e3c38e705b4ce3528',
    messagingSenderId: '358871673337',
    projectId: 'jobscanflutter',
    databaseURL: 'https://jobscanflutter-default-rtdb.firebaseio.com',
    storageBucket: 'jobscanflutter.appspot.com',
    iosClientId: '358871673337-gilg7p7kpiuermrou86a70m2v2m2ssqr.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobscan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwsPicJnpvgyLtiJePcZ4mvHvaSieTwsE',
    appId: '1:358871673337:web:8652806405a6e097ce3528',
    messagingSenderId: '358871673337',
    projectId: 'jobscanflutter',
    authDomain: 'jobscanflutter.firebaseapp.com',
    databaseURL: 'https://jobscanflutter-default-rtdb.firebaseio.com',
    storageBucket: 'jobscanflutter.appspot.com',
  );

}